apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: js19v0l82-nodejs
  janus-idp.io/tekton: js19v0l82-nodejs
  backstage.io/kubernetes-id: js19v0l82-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: js19v0l82-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
