apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: js19v0l82-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: js19v0l82-nodejs 
  name: js19v0l82-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: js19v0l82-nodejs 
